kind: pipeline
type: docker
name: example-PROD


environment:
  APPLICATION_NAME : accountcenter

steps:
  - name: 编译打包代码
    image: maven:3-jdk-10
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - echo ${APPLICATION_NAME}
      - cd  ./service
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

  - name: 构建镜像&PUSH镜像到Hub（PROD）.
    image: plugins/docker
    settings:
      dockerfile: ./release/prod/Dockerfile
      use_cache: true
      repo: registry.cn-hangzhou.aliyuncs.com/windwithlife/accountcenter
      registry: https://registry.cn-hangzhou.aliyuncs.com
      mirror: https://89cgb0wn.mirror.aliyuncs.com
      username: 379163259@qq.com
      password: password7&
      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
      tags:
        - ${DRONE_TAG=latest}
        - build-${DRONE_BUILD_NUMBER}      

  - name: 部署到集群-dron8s方式(PROD)
    image: bh90210/dron8s:latest
    settings:
      yaml: ./release/prod/deployment.yaml
      kubeconfig:
        from_secret: kubeconfig
      app_name: example
      image_name: registry.cn-hangzhou.aliyuncs.com/windwithlife/accountcenter
      soa_gateway: api.koudaibook.com
      soa_gateway_cert: api-koudaibook-cert
      build_tag: build-${DRONE_BUILD_NUMBER}


volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - master
  event:
    - push




---
kind: pipeline
type: docker
name: AccountCenter-UAT

environment:
  APPLICATION_NAME : accountcenter

steps:
  - name: 编译打包代码
    image: maven:3-jdk-10
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - echo ${APPLICATION_NAME}
      - echo $${APPLICATION_NAME}
      - cd  ./service
      - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

  - name: 构建镜像&PUSH镜像到Hub(UAT).
    image: plugins/docker
    settings:
      dockerfile: ./release/prod/Dockerfile
      use_cache: true
      repo: ccr.ccs.tencentyun.com/windwithlife/accountcenter
      registry: https://ccr.ccs.tencentyun.com/
      mirror: https://89cgb0wn.mirror.aliyuncs.com
      username: 100008098144
      password: password7&
      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
      tags:
        - ${DRONE_TAG=latest}
        - build-${DRONE_BUILD_NUMBER}


  - name: 部署到集群-(UAT)
    image: bh90210/dron8s:latest
    settings:
      yaml: ./release/prod/deployment.yaml
      kubeconfig:
        from_secret: kubeconfig
      app_name: accountcenter
      image_name: ccr.ccs.tencentyun.com/windwithlife/accountcenter
      soa_gateway: api.zhangyongqiao.com
      soa_gateway_cert: api-koudaibook-cert
      build_tag: build-${DRONE_BUILD_NUMBER}

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - uat
  event:
    - push
