logging:
  config: /etc/simple/logback-spring.xml


spring:
  datasource:
    url: jdbc:mysql://db.zhangyongqiao.com:3306/userdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Password!&
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: mq.zhangyongqiao.com
    password: 123456
    port: 6379
  


simple:
  domainName: koudaibook.com

qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com