
spring:
  datasource:
    url: jdbc:mysql://47.101.223.234:3306/userdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qazxsw2
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: mq.zhangyongqiao.com
    password: 123456
    port: 6379


simple:
  domainName: koudaibook.com
qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com

#小程序及公众号配置
wechat :
  xcx :
    meetinglive :
      appId: wx57ca96b80dc5cfa8
      appSecret: cc63834a73a0045300d2d6aa3f9a4402
      jscode2session: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
      accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
      getwxacodeunlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=ACCESS_TOKEN
  public:
    publicAppId: "wx84f80fb39e1b266b"
    publicSecret: "6ef821b6d6de49b1210e0a0601fc1493"
    userAauth2: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE&connect_redirect=1#wechat_redirect
    oauthAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
    oauthUserInfo: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
