spring:
  datasource:
    url: jdbc:mysql://db.zhangyongqiao.com:3306/userdb?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root_password
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  redis:
    host: db.zhangyongqiao.com
    password: 12345678
    port: 6379


server:
  port: 5389
simple:
  domainName: koudaibook.com
  common:
    sentry-dsn: https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087
qiniu:
  accessKey: JMVsA4svqk_TUAjq9jOKy0fLVxBaJpiaAAhcn0gr
  secretKey: 39xrdVIpTa65jjPkAB9RCjzdDKN_VY4KdcPkhNjD
  bucket: windwithlife
  domainName: http://images.koudaibook.com

#小程序及公众号配置
wechat :
  xcx :
    meetinglive :
      appId: wx57ca96b80dc5cfa8
      appSecret: cc63834a73a0045300d2d6aa3f9a4402
      jscode2session: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code
      accessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
      getwxacodeunlimit: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=ACCESS_TOKEN
  public:
    publicAppId: "wx84f80fb39e1b266b"
    publicSecret: "6ef821b6d6de49b1210e0a0601fc1493"
    userAauth2: https://open.weixin.qq.com/connect/oauth2/authorize?appid=APPID&redirect_uri=REDIRECT_URI&response_type=code&scope=SCOPE&state=STATE&connect_redirect=1#wechat_redirect
    oauthAccessToken: https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=APPSECRET&code=CODE&grant_type=authorization_code
    oauthUserInfo: https://api.weixin.qq.com/sns/userinfo?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN
